services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8090
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8090:8090"
    volumes:
      - /mnt/main_drive/config/qbittorrent_config:/config
      - /mnt/main_drive/data/torrents:/data/torrents:rw
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    ports:
      - "9696:9696"
    volumes:
      - /mnt/main_drive/config/prowlarr:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    ports:
      - "8989:8989"
    volumes:
      - /mnt/main_drive/config/sonarr:/config
      - /mnt/main_drive/data:/data

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarrr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    ports:
      - "7878:7878"
    volumes:
      - /mnt/main_drive/config/radarr:/config
      - /mnt/main_drive/data:/data

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    ports:
      - "6767:6767"
    volumes:
      - /mnt/main_drive/config/bazarr:/config
      - /mnt/main_drive/data/media/tv:/tv
      - /mnt/main_drive/data/media/movies:/movies
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - JELLYFIN_PublishedServerUrl=http://home-lab.lan/jellyfin
    user: 1000:1000
    volumes:
      - /mnt/main_drive/config/jellyfin/config:/config
      - /mnt/main_drive/config/jellyfin/cache:/cache
      - /mnt/main_drive/data/media:/media
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "8920:8920" # HTTPS
      - "8096:8096" # HTTP
      - "1900:1900/udp"
      - "7359:7359/udp"
    restart: unless-stopped

  jellyseer:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - /mnt/main_drive/config/jellyseerr:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped


  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - FB_BASEURL=/filebrowser
    user: 1000:1000
    ports:
      - "9000:80"
    volumes:
      - /mnt/main_drive:/srv
      - /mnt/main_drive/config/filebrowser:/database
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/main_drive/config/portainer/data:/data
    restart: unless-stopped
